global using BetterBTD.Services.Editor;
global using BetterBTD.Services.MyScripts;
global using BetterBTD.Services.Settings;
global using BetterBTD.Services.Shared;
global using BetterBTD.Services.Shell.Localization;
global using BetterBTD.Services.Start.Capture;
global using BetterBTD.Services.Tasks.CaptureAnalysis;
global using BetterBTD.Services.Tasks.Input;
global using BetterBTD.Services.Tasks.ScriptExecution;
