using System;
using System.Collections.Generic;

namespace BetterBTD.Services.Shell.Localization;

public sealed partial class LocalizationService
{
    private static Dictionary<string, string> BuildZhCnStartResources() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["Start.HeroImageTitle"] = "游戏展示图",
        ["Start.HeroImageHint"] = "（占位图，后续可替换为实际大图）",
        ["Start.ActionPanelTitle"] = "核心功能",
        ["Start.ActionPanelDescription"] = "保持简洁直达，方便在游戏窗口旁快速操作。",
        ["Start.LaunchGame"] = "启动游戏",
        ["Start.LaunchCapture"] = "启动截图器",
        ["Start.StopCapture"] = "停止截图器",
        ["Start.Hint"] = "提示：当前仅完成 UI 设计，按钮逻辑后续接入。",
        ["Start.BannerTitle"] = "BetterBTD",
        ["Start.BannerSubtitle"] = "更好的自动化体验，简洁且可扩展",
        ["Start.BannerLinkText"] = "点击查看文档与教程",
        ["Start.ChangeBanner"] = "更换背景图片",
        ["Start.ResetBanner"] = "恢复默认图片",
        ["Start.CaptureCardTitle"] = "截图器启动",
        ["Start.CaptureCardDescription"] = "截图器启动后才能使用多数自动化功能。",
        ["Start.CaptureModeTitle"] = "截图模式",
        ["Start.CaptureModeDescription"] = "推荐使用 WindowsGraphicsCapture，兼容性和效果更均衡。",
        ["Start.TriggerIntervalTitle"] = "触发器间隔（毫秒）",
        ["Start.TriggerIntervalDescription"] = "默认 50ms，普通用户不建议调整。",
        ["Start.CaptureTestTitle"] = "测试图像捕获",
        ["Start.CaptureTestDescription"] = "测试几种截图模式的效果。",
        ["Start.CaptureTestButtonText"] = "测试图像捕获",
        ["Start.ManualPickWindowTitle"] = "手动选择窗口",
        ["Start.ManualPickWindowDescription"] = "找不到游戏窗口时使用。",
        ["Start.ManualPickWindowButtonText"] = "选择捕获窗口",
        ["Start.AutoFixWin11Title"] = "自动关闭 Win11 窗口优化",
        ["Start.AutoFixWin11Description"] = "修改后重启游戏生效。",
        ["Start.ManualSettings"] = "手动设置",
        ["Start.LinkedStartTitle"] = "同时启动游戏",
        ["Start.LinkedStartDescription"] = "启动截图器时如果游戏未启动，将自动尝试启动。",
        ["Start.InstallPathTitle"] = "游戏安装位置",
        ["Start.InstallPathDescription"] = "选择包含 BloonsTD6.exe 或 BloonsTD6-Epic.exe 的目录。",
        ["Start.Browse"] = "浏览",
        ["Start.SelectInstallPathDialogTitle"] = "选择游戏安装位置",
        ["Start.GameLaunch.AlreadyRunning"] = "游戏已经在运行。",
        ["Start.GameLaunch.Started"] = "游戏已启动。",
        ["Start.GameLaunch.WindowTimeout"] = "已尝试启动游戏，但 {0:F0} 秒内没有找到游戏窗口。",
        ["Start.GameLaunch.CommandSent"] = "游戏启动命令已发送。",
        ["Start.GameLaunch.StartFailed"] = "启动游戏失败：{0}",
        ["Start.GameLaunch.PathRequired"] = "请先选择游戏安装位置。",
        ["Start.GameLaunch.PathNotExecutable"] = "选择的游戏路径不是可执行文件。",
        ["Start.GameLaunch.InstallPathMissing"] = "游戏安装位置不存在。",
        ["Start.GameLaunch.ExecutableNotFound"] = "没有在游戏安装位置找到 BloonsTD6.exe 或 BloonsTD6-Epic.exe。"
    };

    private static Dictionary<string, string> BuildEnUsStartResources() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["Start.HeroImageTitle"] = "Game Hero Image",
        ["Start.HeroImageHint"] = "(placeholder for future artwork)",
        ["Start.ActionPanelTitle"] = "Core Actions",
        ["Start.ActionPanelDescription"] = "Keep key actions simple beside the game window.",
        ["Start.LaunchGame"] = "Launch Game",
        ["Start.LaunchCapture"] = "Launch Capturer",
        ["Start.StopCapture"] = "Stop Capturer",
        ["Start.Hint"] = "Note: this step only provides UI mockup without runtime logic.",
        ["Start.BannerTitle"] = "BetterBTD",
        ["Start.BannerSubtitle"] = "A better automation experience, minimal and extensible",
        ["Start.BannerLinkText"] = "Open docs and tutorials",
        ["Start.ChangeBanner"] = "Change banner image",
        ["Start.ResetBanner"] = "Reset default image",
        ["Start.CaptureCardTitle"] = "Capturer Startup",
        ["Start.CaptureCardDescription"] = "Most automation features require the capturer to be running.",
        ["Start.CaptureModeTitle"] = "Capture Mode",
        ["Start.CaptureModeDescription"] = "WindowsGraphicsCapture is recommended for better overall compatibility and results.",
        ["Start.TriggerIntervalTitle"] = "Trigger Interval (ms)",
        ["Start.TriggerIntervalDescription"] = "Default is 50ms; regular users should keep this value.",
        ["Start.CaptureTestTitle"] = "Capture Test",
        ["Start.CaptureTestDescription"] = "Test capture quality in several modes.",
        ["Start.CaptureTestButtonText"] = "Test Capture",
        ["Start.ManualPickWindowTitle"] = "Manual Window Pick",
        ["Start.ManualPickWindowDescription"] = "Use this if the game window is not found.",
        ["Start.ManualPickWindowButtonText"] = "Pick Capture Window",
        ["Start.AutoFixWin11Title"] = "Auto Fix Win11 Window Optimization",
        ["Start.AutoFixWin11Description"] = "Restart game after applying this setting.",
        ["Start.ManualSettings"] = "Manual Setting",
        ["Start.LinkedStartTitle"] = "Launch Game Together",
        ["Start.LinkedStartDescription"] = "When starting capturer, launch game automatically if needed.",
        ["Start.InstallPathTitle"] = "Game Install Path",
        ["Start.InstallPathDescription"] = "Select the folder containing BloonsTD6.exe or BloonsTD6-Epic.exe.",
        ["Start.Browse"] = "Browse",
        ["Start.SelectInstallPathDialogTitle"] = "Select Game Install Path",
        ["Start.GameLaunch.AlreadyRunning"] = "Game is already running.",
        ["Start.GameLaunch.Started"] = "Game has started.",
        ["Start.GameLaunch.WindowTimeout"] = "Tried to launch the game, but no game window was found within {0:F0} seconds.",
        ["Start.GameLaunch.CommandSent"] = "Game launch command was sent.",
        ["Start.GameLaunch.StartFailed"] = "Failed to launch game: {0}",
        ["Start.GameLaunch.PathRequired"] = "Select the game install path first.",
        ["Start.GameLaunch.PathNotExecutable"] = "The selected game path is not an executable file.",
        ["Start.GameLaunch.InstallPathMissing"] = "The game install path does not exist.",
        ["Start.GameLaunch.ExecutableNotFound"] = "BloonsTD6.exe or BloonsTD6-Epic.exe was not found in the game install path."
    };
}
