using System;
using System.Collections.Generic;

namespace BetterBTD.Services.Shell.Localization;

public sealed partial class LocalizationService
{
    private static Dictionary<string, string> BuildZhCnToolsResources() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["Tools.PageTitle"] = "小工具",
        ["Tools.PageDescription"] = "提供回合、英雄等级和模范度相关的计算工具。",
        ["Tools.Section.Parameters"] = "参数",
        ["Tools.Section.ParametersDescription"] = "展开后可查看并编辑当前计算参数。",
        ["Tools.Section.Result"] = "计算结果",
        ["Tools.Section.ResultDescription"] = "根据当前参数实时显示计算结果。",
        ["Tools.Action.Calculate"] = "计算",

        ["Tools.Round.Title"] = "回合计算器",
        ["Tools.Round.Description"] = "根据起始回合和结束回合，统计区间内的现金、经验、RBE、耗时和主要气球构成。",
        ["Tools.Round.StartRound"] = "起始回合",
        ["Tools.Round.StartRoundDescription"] = "计算开始的回合编号。",
        ["Tools.Round.EndRound"] = "结束回合",
        ["Tools.Round.EndRoundDescription"] = "计算结束的回合编号。",
        ["Tools.Round.Result.InvalidRange"] = "结束回合不能小于起始回合。当前数据可用范围为 1 到 {0}。",
        ["Tools.Round.Result.LoadFailed"] = "回合数据加载失败：{0}",
        ["Tools.Round.Result.LoadFailedReason"] = "无法读取回合数据文件",
        ["Tools.Round.Result.Range"] = "区间：第 {0} 回合到第 {1} 回合，共 {2} 回合",
        ["Tools.Round.Result.TotalCashReward"] = "总现金收益：{0}",
        ["Tools.Round.Result.TotalExperience"] = "总经验：{0}",
        ["Tools.Round.Result.TotalRbe"] = "总 RBE：{0}",
        ["Tools.Round.Result.TotalDuration"] = "总持续时间：{0}",
        ["Tools.Round.Result.AveragePerRound"] = "平均每回合：现金 {0}，经验 {1}，RBE {2}，耗时 {3}",
        ["Tools.Round.Result.PeakCashReward"] = "单回合最高现金：第 {0} 回合，{1}",
        ["Tools.Round.Result.PeakRbe"] = "单回合最高 RBE：第 {0} 回合，{1}",
        ["Tools.Round.Result.PeakDuration"] = "单回合最长耗时：第 {0} 回合，{1}",
        ["Tools.Round.Result.TopBloons"] = "主要气球构成：{0}",
        ["Tools.Round.Result.TopBloonItem"] = "{0} ×{1}",
        ["Tools.Round.Result.NoBloons"] = "无气球数据",
        ["Tools.Round.Result.DurationSeconds"] = "{0} 秒",
        ["Tools.Round.Result.DurationMinutesSeconds"] = "{0} 分 {1:00}.{2:00} 秒",
        ["Tools.Round.BloonModifier.Camo"] = "迷彩",
        ["Tools.Round.BloonModifier.Fortified"] = "强化",
        ["Tools.Round.BloonModifier.Regrow"] = "重生",
        ["Tools.Round.BloonType.Red"] = "红气球",
        ["Tools.Round.BloonType.Blue"] = "蓝气球",
        ["Tools.Round.BloonType.Green"] = "绿气球",
        ["Tools.Round.BloonType.Yellow"] = "黄气球",
        ["Tools.Round.BloonType.Pink"] = "粉气球",
        ["Tools.Round.BloonType.Black"] = "黑气球",
        ["Tools.Round.BloonType.White"] = "白气球",
        ["Tools.Round.BloonType.Purple"] = "紫气球",
        ["Tools.Round.BloonType.Zebra"] = "斑马气球",
        ["Tools.Round.BloonType.Lead"] = "铅气球",
        ["Tools.Round.BloonType.Rainbow"] = "彩虹气球",
        ["Tools.Round.BloonType.Ceramic"] = "陶瓷气球",
        ["Tools.Round.BloonType.Moab"] = "MOAB",
        ["Tools.Round.BloonType.Bfb"] = "BFB",
        ["Tools.Round.BloonType.Zomg"] = "ZOMG",
        ["Tools.Round.BloonType.Ddt"] = "DDT",
        ["Tools.Round.BloonType.Bad"] = "BAD",

        ["Tools.Hero.Title"] = "英雄等级计算器",
        ["Tools.Hero.Description"] = "根据英雄与放置回合，推算目标回合或目标等级中的另一项。",
        ["Tools.Hero.Hero"] = "英雄",
        ["Tools.Hero.HeroDescription"] = "选择需要查看等级成长的英雄。",
        ["Tools.Hero.PlacementRound"] = "放置回合",
        ["Tools.Hero.PlacementRoundDescription"] = "英雄实际落地的回合。",
        ["Tools.Hero.TargetRound"] = "目标回合",
        ["Tools.Hero.TargetRoundDescription"] = "填写后，后续可反推该回合能达到的等级。",
        ["Tools.Hero.TargetLevel"] = "目标等级",
        ["Tools.Hero.TargetLevelDescription"] = "填写后，后续可反推达到该等级所需的回合。",
        ["Tools.Hero.Hint"] = "目标回合与目标等级任选其一填写。",
        ["Tools.Hero.Result.NoTarget"] = "请选择英雄，并填写目标回合或目标等级中的任意一项。",
        ["Tools.Hero.Result.TargetRound"] = "已记录 {0}，放置回合 {1}，目标回合 {2}。后续将计算对应等级。",
        ["Tools.Hero.Result.TargetLevel"] = "已记录 {0}，放置回合 {1}，目标等级 {2}。后续将计算所需回合。",
        ["Tools.Hero.Result.BothTargets"] = "目标回合与目标等级同时填写时，后续会校验优先级与冲突。",

        ["Tools.Paragon.Title"] = "模范等级计算器",
        ["Tools.Paragon.Description"] = "根据模范猴子、总击破、升级数和额外投入现金，后续计算模范度。",
        ["Tools.Paragon.Monkey"] = "模范猴子",
        ["Tools.Paragon.MonkeyDescription"] = "选择要估算模范度的猴子。",
        ["Tools.Paragon.TotalPops"] = "总击破数",
        ["Tools.Paragon.TotalPopsDescription"] = "用于模范度计算的累计击破数。",
        ["Tools.Paragon.UpgradeCount"] = "升级总数",
        ["Tools.Paragon.UpgradeCountDescription"] = "用于模范度计算的总升级次数。",
        ["Tools.Paragon.ExtraCash"] = "额外现金",
        ["Tools.Paragon.ExtraCashDescription"] = "用于模范度计算的额外投入现金。",
        ["Tools.Paragon.ResultPlaceholder"] = "已记录 {0} 参数：击破 {1}，升级 {2}，额外现金 {3}。具体 degree 公式待接入。"
    };

    private static Dictionary<string, string> BuildEnUsToolsResources() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["Tools.PageTitle"] = "Tools",
        ["Tools.PageDescription"] = "Utility calculators for rounds, hero levels, and paragons.",
        ["Tools.Section.Parameters"] = "Parameters",
        ["Tools.Section.ParametersDescription"] = "Expand to inspect and edit the current calculator inputs.",
        ["Tools.Section.Result"] = "Result",
        ["Tools.Section.ResultDescription"] = "Shows the live calculation result for the current inputs.",
        ["Tools.Action.Calculate"] = "Calculate",

        ["Tools.Round.Title"] = "Round Calculator",
        ["Tools.Round.Description"] = "Summarize cash, XP, RBE, duration, and major bloon composition for a round range.",
        ["Tools.Round.StartRound"] = "Start Round",
        ["Tools.Round.StartRoundDescription"] = "Round number where the calculation begins.",
        ["Tools.Round.EndRound"] = "End Round",
        ["Tools.Round.EndRoundDescription"] = "Round number where the calculation ends.",
        ["Tools.Round.Result.InvalidRange"] = "End round cannot be earlier than start round. Available data range: 1 to {0}.",
        ["Tools.Round.Result.LoadFailed"] = "Failed to load round data: {0}",
        ["Tools.Round.Result.LoadFailedReason"] = "round data file is unavailable",
        ["Tools.Round.Result.Range"] = "Range: round {0} to round {1}, {2} rounds total",
        ["Tools.Round.Result.TotalCashReward"] = "Total cash reward: {0}",
        ["Tools.Round.Result.TotalExperience"] = "Total XP: {0}",
        ["Tools.Round.Result.TotalRbe"] = "Total RBE: {0}",
        ["Tools.Round.Result.TotalDuration"] = "Total duration: {0}",
        ["Tools.Round.Result.AveragePerRound"] = "Average per round: cash {0}, XP {1}, RBE {2}, duration {3}",
        ["Tools.Round.Result.PeakCashReward"] = "Highest single-round cash: round {0}, {1}",
        ["Tools.Round.Result.PeakRbe"] = "Highest single-round RBE: round {0}, {1}",
        ["Tools.Round.Result.PeakDuration"] = "Longest single-round duration: round {0}, {1}",
        ["Tools.Round.Result.TopBloons"] = "Top bloon composition: {0}",
        ["Tools.Round.Result.TopBloonItem"] = "{0} x{1}",
        ["Tools.Round.Result.NoBloons"] = "No bloon data",
        ["Tools.Round.Result.DurationSeconds"] = "{0}s",
        ["Tools.Round.Result.DurationMinutesSeconds"] = "{0}m {1:00}.{2:00}s",
        ["Tools.Round.BloonModifier.Camo"] = "Camo",
        ["Tools.Round.BloonModifier.Fortified"] = "Fortified",
        ["Tools.Round.BloonModifier.Regrow"] = "Regrow",
        ["Tools.Round.BloonType.Red"] = "Red Bloon",
        ["Tools.Round.BloonType.Blue"] = "Blue Bloon",
        ["Tools.Round.BloonType.Green"] = "Green Bloon",
        ["Tools.Round.BloonType.Yellow"] = "Yellow Bloon",
        ["Tools.Round.BloonType.Pink"] = "Pink Bloon",
        ["Tools.Round.BloonType.Black"] = "Black Bloon",
        ["Tools.Round.BloonType.White"] = "White Bloon",
        ["Tools.Round.BloonType.Purple"] = "Purple Bloon",
        ["Tools.Round.BloonType.Zebra"] = "Zebra Bloon",
        ["Tools.Round.BloonType.Lead"] = "Lead Bloon",
        ["Tools.Round.BloonType.Rainbow"] = "Rainbow Bloon",
        ["Tools.Round.BloonType.Ceramic"] = "Ceramic Bloon",
        ["Tools.Round.BloonType.Moab"] = "MOAB",
        ["Tools.Round.BloonType.Bfb"] = "BFB",
        ["Tools.Round.BloonType.Zomg"] = "ZOMG",
        ["Tools.Round.BloonType.Ddt"] = "DDT",
        ["Tools.Round.BloonType.Bad"] = "BAD",

        ["Tools.Hero.Title"] = "Hero Level Calculator",
        ["Tools.Hero.Description"] = "Use hero and placement round to infer either target round or target level from the other field.",
        ["Tools.Hero.Hero"] = "Hero",
        ["Tools.Hero.HeroDescription"] = "Select the hero whose XP curve you want to inspect.",
        ["Tools.Hero.PlacementRound"] = "Placement Round",
        ["Tools.Hero.PlacementRoundDescription"] = "Round where the hero is placed.",
        ["Tools.Hero.TargetRound"] = "Target Round",
        ["Tools.Hero.TargetRoundDescription"] = "Fill this to later infer the reached level at that round.",
        ["Tools.Hero.TargetLevel"] = "Target Level",
        ["Tools.Hero.TargetLevelDescription"] = "Fill this to later infer the round required to reach that level.",
        ["Tools.Hero.Hint"] = "Fill either target round or target level.",
        ["Tools.Hero.Result.NoTarget"] = "Select a hero and fill either target round or target level.",
        ["Tools.Hero.Result.TargetRound"] = "Recorded {0}, placement round {1}, target round {2}. The matching level will be computed later.",
        ["Tools.Hero.Result.TargetLevel"] = "Recorded {0}, placement round {1}, target level {2}. The required round will be computed later.",
        ["Tools.Hero.Result.BothTargets"] = "When both target round and target level are filled, later formula integration will resolve priority and conflicts.",

        ["Tools.Paragon.Title"] = "Paragon Degree Calculator",
        ["Tools.Paragon.Description"] = "Use paragon monkey, total pops, upgrade count, and extra cash to calculate degree later.",
        ["Tools.Paragon.Monkey"] = "Paragon Monkey",
        ["Tools.Paragon.MonkeyDescription"] = "Select the monkey to estimate paragon degree for.",
        ["Tools.Paragon.TotalPops"] = "Total Pops",
        ["Tools.Paragon.TotalPopsDescription"] = "Accumulated pop count used by the degree calculation.",
        ["Tools.Paragon.UpgradeCount"] = "Upgrade Count",
        ["Tools.Paragon.UpgradeCountDescription"] = "Total number of upgrades used by the degree calculation.",
        ["Tools.Paragon.ExtraCash"] = "Extra Cash",
        ["Tools.Paragon.ExtraCashDescription"] = "Additional injected cash used by the degree calculation.",
        ["Tools.Paragon.ResultPlaceholder"] = "Recorded {0} inputs: pops {1}, upgrades {2}, extra cash {3}. Degree formula pending."
    };
}
