using System;
using System.Collections.Generic;

namespace BetterBTD.Services.Shell.Localization;

public sealed partial class LocalizationService
{
    private static Dictionary<string, string> BuildZhCnLibraryResources() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["Library.Page.Title"] = "我的脚本",
        ["Library.Page.Subtitle"] = "使用受管资源库统一管理脚本，并为自动任务配置脚本槽位。",
        ["Library.Action.Import"] = "导入脚本",
        ["Library.Action.Export"] = "导出脚本",
        ["Library.Action.Remove"] = "删除脚本",
        ["Library.Action.Refresh"] = "刷新",
        ["Library.Action.Bind"] = "绑定到槽位",
        ["Library.Action.ClearBinding"] = "清除绑定",
        ["Library.Filters.Title"] = "筛选",
        ["Library.Filters.Search"] = "搜索脚本",
        ["Library.Filters.Search.Placeholder"] = "名称、标签、地图",
        ["Library.Filters.Map"] = "地图",
        ["Library.Filters.Difficulty"] = "难度",
        ["Library.Filters.Mode"] = "模式",
        ["Library.Filters.TaskKind"] = "任务类型",
        ["Library.TaskKind.Custom"] = "自定义",
        ["Library.TaskKind.Collection"] = "刷收集",
        ["Library.TaskKind.BlackBorder"] = "刷黑框",
        ["Library.TaskKind.Race"] = "竞速",
        ["Library.Filters.SlotSearch"] = "搜索槽位",
        ["Library.Filters.All"] = "全部",
        ["Library.Section.Scripts"] = "脚本资源",
        ["Library.Section.Slots"] = "任务槽位",
        ["Library.Empty.Scripts"] = "当前没有已导入脚本。",
        ["Library.Empty.Slots"] = "当前筛选条件下没有槽位。",
        ["Library.Column.Name"] = "名称",
        ["Library.Column.Map"] = "地图",
        ["Library.Column.Difficulty"] = "难度",
        ["Library.Column.Mode"] = "模式",
        ["Library.Column.Tags"] = "标签",
        ["Library.Column.Bindings"] = "绑定数",
        ["Library.Column.State"] = "状态",
        ["Library.Column.Group"] = "分组",
        ["Library.Column.Slot"] = "槽位",
        ["Library.Column.BoundScript"] = "当前脚本",
        ["Library.State.Ready"] = "正常",
        ["Library.State.MetadataIssue"] = "元数据异常",
        ["Library.State.MissingFile"] = "资源丢失",
        ["Library.State.Unbound"] = "未绑定",
        ["Library.State.BrokenBinding"] = "绑定失效",
        ["Library.State.Placeholder"] = "占位槽位",
        ["Library.State.Bound"] = "已绑定",
        ["Library.Summary.None"] = "未选择脚本。",
        ["Library.Summary.Script"] = "来源文件：{0}  |  内部标识：{1}",
        ["Library.Dialog.Remove.Title"] = "删除脚本",
        ["Library.Dialog.Remove.Message"] = "删除后会同时清除相关槽位绑定。是否继续？",
        ["Library.Dialog.ImportError.Title"] = "导入失败",
        ["Library.Dialog.ExportError.Title"] = "导出失败",
        ["Library.Dialog.RemoveError.Title"] = "删除失败",
        ["Library.Dialog.BindingError.Title"] = "绑定失败",
        ["Library.Dialog.Primary"] = "确定",
        ["Library.Dialog.Cancel"] = "取消",
        ["Library.File.ImportFilter"] = "BetterBTD Script (*.btd;*.json)|*.btd;*.json|All Files (*.*)|*.*",
        ["Library.File.ExportFilter"] = "BetterBTD Script (*.btd)|*.btd|JSON File (*.json)|*.json|All Files (*.*)|*.*"
    };

    private static Dictionary<string, string> BuildEnUsLibraryResources() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["Library.Page.Title"] = "My Scripts",
        ["Library.Page.Subtitle"] = "Manage scripts as internal assets and bind them to auto-task slots.",
        ["Library.Action.Import"] = "Import Script",
        ["Library.Action.Export"] = "Export Script",
        ["Library.Action.Remove"] = "Remove Script",
        ["Library.Action.Refresh"] = "Refresh",
        ["Library.Action.Bind"] = "Bind To Slot",
        ["Library.Action.ClearBinding"] = "Clear Binding",
        ["Library.Filters.Title"] = "Filters",
        ["Library.Filters.Search"] = "Search Scripts",
        ["Library.Filters.Search.Placeholder"] = "Name, tags, map",
        ["Library.Filters.Map"] = "Map",
        ["Library.Filters.Difficulty"] = "Difficulty",
        ["Library.Filters.Mode"] = "Mode",
        ["Library.Filters.TaskKind"] = "Task Kind",
        ["Library.TaskKind.Custom"] = "Custom",
        ["Library.TaskKind.Collection"] = "Collection",
        ["Library.TaskKind.BlackBorder"] = "Black Border",
        ["Library.TaskKind.Race"] = "Race",
        ["Library.Filters.SlotSearch"] = "Search Slots",
        ["Library.Filters.All"] = "All",
        ["Library.Section.Scripts"] = "Managed Scripts",
        ["Library.Section.Slots"] = "Task Slots",
        ["Library.Empty.Scripts"] = "No imported scripts were found.",
        ["Library.Empty.Slots"] = "No slots match the current filters.",
        ["Library.Column.Name"] = "Name",
        ["Library.Column.Map"] = "Map",
        ["Library.Column.Difficulty"] = "Difficulty",
        ["Library.Column.Mode"] = "Mode",
        ["Library.Column.Tags"] = "Tags",
        ["Library.Column.Bindings"] = "Bindings",
        ["Library.Column.State"] = "State",
        ["Library.Column.Group"] = "Group",
        ["Library.Column.Slot"] = "Slot",
        ["Library.Column.BoundScript"] = "Bound Script",
        ["Library.State.Ready"] = "Ready",
        ["Library.State.MetadataIssue"] = "Metadata Issue",
        ["Library.State.MissingFile"] = "Missing Asset",
        ["Library.State.Unbound"] = "Unbound",
        ["Library.State.BrokenBinding"] = "Broken Binding",
        ["Library.State.Placeholder"] = "Placeholder Slot",
        ["Library.State.Bound"] = "Bound",
        ["Library.Summary.None"] = "No script selected.",
        ["Library.Summary.Script"] = "Source File: {0}  |  Internal Id: {1}",
        ["Library.Dialog.Remove.Title"] = "Remove Script",
        ["Library.Dialog.Remove.Message"] = "This also clears related slot bindings. Continue?",
        ["Library.Dialog.ImportError.Title"] = "Import Failed",
        ["Library.Dialog.ExportError.Title"] = "Export Failed",
        ["Library.Dialog.RemoveError.Title"] = "Remove Failed",
        ["Library.Dialog.BindingError.Title"] = "Binding Failed",
        ["Library.Dialog.Primary"] = "OK",
        ["Library.Dialog.Cancel"] = "Cancel",
        ["Library.File.ImportFilter"] = "BetterBTD Script (*.btd;*.json)|*.btd;*.json|All Files (*.*)|*.*",
        ["Library.File.ExportFilter"] = "BetterBTD Script (*.btd)|*.btd|JSON File (*.json)|*.json|All Files (*.*)|*.*"
    };
}
